resources:
  jobs:
    finhive_ingest_fred:
      name: finhive_ingest_fred
      schedule:
        quartz_cron_expression: 0 30 16 ? * MON-FRI
        timezone_id: America/New_York
        pause_status: UNPAUSED
      tasks:
        - task_key: ingest_fred
          notebook_task:
            notebook_path: /Workspace/Shared/finhive-2026/notebooks/data_ingestion/fred/orchestrator
            base_parameters:
              job_name: "{{job.name}}"
            source: WORKSPACE
          environment_key: ingestion
      queue:
        enabled: true
      environments:
        - environment_key: ingestion
          spec:
            client: "3"
            dependencies:
              - fredapi
      performance_target: PERFORMANCE_OPTIMIZED